# Generated by Django 5.0 on 2023-12-30 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='Post-Images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikedBy',
            field=models.ManyToManyField(blank=True, related_name='dislikedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='likedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
